version: '3.8'

services:
  db:
    build:
      context: ./db   
    container_name: automata-db
    restart: always
    environment:
      POSTGRES_USER: automatauser
      POSTGRES_PASSWORD: automatapassword
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data   
    command: ["postgres"]

  backend:
    build:
      context: ./backend   
    container_name: automata-backend
    restart: always
    environment:
      CURRENT_ENV: dev
    depends_on:
      - db
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  frontend:
    build:
      context: ./frontend
    container_name: automata-frontend
    restart: always
    environment:
      CURRENT_ENV: docker
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data:
